import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8081/sign-in');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@prueba.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('prueba');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Show navigation menu' }).click();
  await page.getByText('Chatbot').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Eliminar' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).fill('Normas de la piscina');
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).click();
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).fill('La piscina abre a las');
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).fill('Horario de la piscina');
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).click();
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).fill('La piscina abre a las 9:00 am\nLa piscina cierra a las 10:00 pm');
  await page.getByRole('button', { name: 'Indexar información' }).click();
  await page.getByRole('button', { name: 'Indexar información' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).fill('a');
  await page.getByRole('button', { name: 'Indexar información' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).click();
  await page.getByRole('textbox', { name: 'Ej: Normas de convivencia' }).fill('');
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).click();
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).fill('a');
  await page.getByRole('button', { name: 'Indexar información' }).click();
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).click();
  await page.getByRole('textbox', { name: 'Pega aquí el contenido del' }).fill('');
});