from fastapi.testclient import TestClient
from uuid import uuid4
import pytest
from main import app
from core.deps import get_current_user, get_supabase

client = TestClient(app)

# Mocked user data
mock_user = {
    "id": str(uuid4()),
    "username": "testuser",
    "avatar_url": None,
    "created_at": "2026-02-22T00:00:00Z"
}

# Dummy Supabase mock class
class MockSupabaseTable:
    def __init__(self, table_name, data):
        self.table_name = table_name
        self._data = data

    def select(self, *args, **kwargs):
        self._operation = "select"
        return self

    def insert(self, *args, **kwargs):
        self._operation = "insert"
        from uuid import uuid4
        from datetime import datetime
        # Dummy behavior - populate missing fields generated by DB
        inserted_row = args[0].copy()
        if "id" not in inserted_row:
            inserted_row["id"] = str(uuid4())
        if "created_at" not in inserted_row:
            inserted_row["created_at"] = datetime.utcnow().isoformat() + "Z"
            
        self._inserted = [inserted_row]
        return self

    def eq(self, *args, **kwargs):
        return self
        
    def in_(self, *args, **kwargs):
        return self
        
    def order(self, *args, **kwargs):
        return self

    def execute(self):
        class MockResponse:
            def __init__(self, data):
                self.data = data
        
        if self._operation == "insert":
            return MockResponse(self._inserted)
        return MockResponse(self._data)

class MockSupabaseClient:
    def __init__(self, mock_responses):
        self.mock_responses = mock_responses

    def table(self, name: str):
        return MockSupabaseTable(name, self.mock_responses.get(name, []))

# Dependency overrides
def override_get_current_user():
    return mock_user

mock_channel_id = str(uuid4())

def override_get_supabase():
    # Retornar arrays con objetos adecuados según lo que esperan los routers
    return MockSupabaseClient({
        "channel_participants": [{"channel_id": mock_channel_id}],
        "chat_channels": [{"id": mock_channel_id, "community_id": str(uuid4()), "name": "General", "is_direct_message": False}],
        "messages": [{"id": str(uuid4()), "channel_id": mock_channel_id, "sender_id": mock_user["id"], "content": "Hello", "created_at": "2026-02-22T00:00:00Z", "sender": mock_user}]
    })

@pytest.fixture(autouse=True)
def setup_overrides():
    app.dependency_overrides[get_current_user] = override_get_current_user
    app.dependency_overrides[get_supabase] = override_get_supabase
    yield
    app.dependency_overrides.clear()

def test_get_channels():
    response = client.get("/chat/channels")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    assert len(data) == 1
    assert data[0]["name"] == "General"

def test_get_channel_messages():
    response = client.get(f"/chat/channels/{mock_channel_id}/messages")
    assert response.status_code == 200
    data = response.json()
    assert isinstance(data, list)
    assert len(data) == 1
    assert data[0]["content"] == "Hello"

def test_send_message():
    new_msg = {
        "channel_id": mock_channel_id,
        "content": "New test message"
    }
    response = client.post(f"/chat/channels/{mock_channel_id}/messages", json=new_msg)
    assert response.status_code == 200
    data = response.json()
    assert data["content"] == "New test message"
    assert data["channel_id"] == mock_channel_id
    assert data["sender_id"] == mock_user["id"]
